### ISSUE TITLE
Add my blog post as guide

### ISSUE THREAD

**Issue by iacore** [greenfork/jzignet#3]
While it is not a tutorial on how to use Janet with Zig, it does come with a working repository.

https://www.1a-insec.net/blog/16-buy-janet-get-gc-free/
https://git.envs.net/iacore/janet-zig-test

Maybe you can put this in the project readme?

**Comment by greenfork** [comment]
Sure, I'm a bit busy right now, will add this and review everything else in a couple of days, thanks a lot!

**Comment by greenfork** [comment]
Added, thanks! https://github.com/greenfork/jzignet/commit/cc793af6050be2e19c2271ad051524913a16face
