### ISSUE TITLE
Tip on @import("../xxx") outside of package path

### ISSUE THREAD

**Issue by iacore** [greenfork/jzignet#6]
To import a file outside of package path, create a symlink first, and import that symlink.

Example:

```
ln -s ../lib/foo lib_foo
```

```zig
_ = @import("lib_foo/build/zig");
```

**Comment by greenfork** [comment]
Do you think I can use it somewhere in the project right now, after we have merged your PR about moving the example's build file inside the main file?

**Comment by iacore** [comment]
Not right now. I found out this trick after the PR.

P.S. you may want to move this to Discussions (enable it first for this project).
